name: flutter_editor
description: "A new Flutter package project."
version: 0.1.0
publish_to: https://pub.fittin.ru
homepage: https://github.com/ManIlya/flutter_editor.git
repository: https://github.com/ManIlya/flutter_editor.git

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  float_column: ^4.0.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5
  html: ^0.15.4

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: